/*
 *Even Fibonacci Numbers
 *Problem 2
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main()
{
    long long first = 1;
    long long second = 2;
    long long next = first + second;
    long long sum = 2;

    while (next <= 4000000)
    {
        if (next % 2 == 0)
        {
            sum += next;
        }
        first = second;
        second = next;
        next = first + second;
    }
    printf("The sum of even-valued fibonacci numbers below 4 million is: %lld\n", sum); // Answer:

    return 0;
}